# Generated by Django 4.2.27 on 2025-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('boutiquier', 'Boutiquier'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
