# Generated by Django 4.2.27 on 2025-12-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
        ('accounts', '0003_client_is_shop_owner_alter_client_pays_and_more'),
    ]

    operations = [
    ]
