"""
Django settings for ECOMMERCE project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIRS = os.path.join(BASE_DIR, 'templates')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sons7^ce+7^^=idr)tyo7&anri)s_mtn_-&w$^g6os41!24vw_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'BRYSHOP',
    'accounts',
    
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'ECOMMERCE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'BRYSHOP.context_processors.categories_processor',
            ],
        },
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
    },
]

WSGI_APPLICATION = 'ECOMMERCE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import sys

# Détecter si on exécute des tests
TESTING = 'test' in sys.argv

if TESTING:
    # Utiliser SQLite en mémoire pour les tests (plus rapide, pas besoin de PostgreSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    # Utiliser PostgreSQL pour le développement et la production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME', 'BryshopDB'),
            'USER': os.environ.get('DATABASE_USER', 'postgres'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),  # Pas de mot de passe
            'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Simplifier le hashage des mots de passe pendant les tests pour accélérer
if TESTING:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirection après connexion / déconnexion
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login'

AUTH_USER_MODEL = 'accounts.CustomUser'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'djikissibryan@gmail.com'
EMAIL_HOST_PASSWORD = 'cuwi gnjm vylz yhmq'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Pour styliser avec Bootstrap si besoin
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Assurer que le dossier logs existe
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Configuration des logs pour Logstash / Filebeat
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '{"time": "%(asctime)s", "level": "%(levelname)s", "message": "%(message)s"}'
        },
        'standard': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django_errors.log') if not os.path.exists('/app') else '/app/logs/django_errors.log',
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Notch Pay Configuration
NOTCH_PAY_PUBLIC_KEY = 'pk_test.xQprqgaLJHJAJZ8XBPE9mn9bJJWbb3ExKvlaJupHI8p76LjHkO6fuDNKcKDYuEekWVCSEAfq18JPU11tolJ8oEtHSYWIMqGRk4FDc0nqLwpOBxc844FtPY0IrZmNq'
NOTCH_PAY_URL = 'https://api.notchpay.co/payments/initialize'
NOTCH_PAY_VERIFY_URL = 'https://api.notchpay.co/payments/'
  # À remplacer par votre domaine réel

# Configuration Jazzmin pour BryShop
JAZZMIN_SETTINGS = {
    # Titre du site
    "site_title": "BryShop Admin",
    "site_header": "BryShop",
    "site_brand": "BryShop Administration",
    "site_logo": None,  # Chemin vers ton logo (ex: "images/logo.png")
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Message de bienvenue sur l'écran de connexion
    "welcome_sign": "Bienvenue sur BryShop Admin",
    
    # Copyright dans le footer
    "copyright": "BryShop © 2025",
    
    # Recherche dans le modèle depuis la barre latérale
    "search_model": ["auth.User", "BRYSHOP.Product"],
    
    # Nom du champ à utiliser pour l'utilisateur
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Liens dans le menu supérieur
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le site", "url": "/", "new_window": True},
        {"model": "auth.User"},
        {"app": "BRYSHOP"},
    ],
    
    #############
    # User Menu #
    #############
    
    # Liens supplémentaires à inclure dans le menu utilisateur
    "usermenu_links": [
        {"name": "Voir le site", "url": "/", "new_window": True},
        {"model": "auth.user"}
    ],
    
    #############
    # Side Menu #
    #############
    
    # Afficher le nom du sidebar ou non
    "show_sidebar": True,
    
    # Toujours afficher le menu latéral (sinon il est caché sur mobile)
    "navigation_expanded": True,
    
    # Masquer les applications et les modèles
    "hide_apps": [],
    "hide_models": [],
    
    # Ordre des applications dans le menu latéral
    "order_with_respect_to": ["auth", "BRYSHOP", "accounts"],
    
    # Icônes personnalisées pour les applications/modèles
    # https://fontawesome.com/icons?d=gallery&m=free
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "BRYSHOP.Product": "fas fa-box",
        "BRYSHOP.Category": "fas fa-tags",
        "BRYSHOP.Cart": "fas fa-shopping-cart",
        "BRYSHOP.Order": "fas fa-file-invoice",
        
        "accounts.Client": "fas fa-user-tie",
    },
    
    # Icônes pour les modèles (même format que ci-dessus)
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # Related Modal #
    #################
    
    # Utiliser des modales au lieu de popups
    "related_modal_active": False,
    
    #############
    # UI Tweaks #
    #############
    
    # Personnalisation CSS/JS relative aux modèles et/ou applications
    "custom_css": None,
    "custom_js": None,
    
    # Afficher le bouton de navigation latéral
    "show_ui_builder": False,
    
    ###############
    # Change view #
    ###############
    
    # Rendu du formulaire de changement en mode simple ou onglets
    "changeform_format": "horizontal_tabs",
    
    # Remplacer les changelist avec des vues personnalisées
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    
    # Ajouter un bouton de langue
    "language_chooser": False,
}

# Configuration des couleurs et du thème
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",  # Vert pour BryShop
    "accent": "accent-success",  # Vert accent
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",  # Sidebar vert foncé
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # Options: default, cerulean, cosmo, etc.
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}
