# Generated by Django 5.2.9 on 2025-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0006_remove_cart_items_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numero_commande',
            field=models.CharField(default='CMD-###', editable=False, max_length=50, unique=True),
        ),
    ]
