# Generated by Django 5.2.9 on 2025-12-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0007_order_numero_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traitement', 'En traitement'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
