# Generated by Django 5.2.9 on 2025-12-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0009_order_address_order_email_order_nom_order_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
