# Generated by Django 5.2.9 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0010_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
