# Generated by Django 5.2.9 on 2025-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0011_order_frais_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire')], default='livraison', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
    ]
