# Generated by Django 4.2.27 on 2025-12-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0007_payment_order_payment'),
        ('BRYSHOP', '0012_order_mode_paiement_order_statut_paiement'),
    ]

    operations = [
    ]
