# Generated by Django 4.2.27 on 2025-12-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0013_merge_20251216_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notch_pay_id',
            field=models.CharField(blank=True, help_text='ID unique de la transaction Notch Pay', max_length=100, null=True),
        ),
    ]
