# Generated by Django 4.2.27 on 2025-12-16 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BRYSHOP', '0014_fix_payment_notch_pay_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(help_text='Token sécurisé fourni par le gateway de paiement', max_length=255, unique=True)),
                ('last_four_digits', models.CharField(help_text='4 derniers chiffres de la carte', max_length=4)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Autre')], default='other', max_length=20)),
                ('expiry_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2050)])),
                ('cardholder_name', models.CharField(help_text='Nom du titulaire de la carte', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Carte par défaut pour les paiements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'card_token')},
            },
        ),
    ]
