# Generated by Django 4.2.27 on 2025-12-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0015_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_card',
            field=models.ForeignKey(blank=True, help_text='Carte bancaire utilisée pour le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='BRYSHOP.usercard'),
        ),
    ]
