# Generated by Django 4.2.27 on 2025-12-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0016_payment_user_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_card',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
