# Generated by Django 4.2.27 on 2025-12-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRYSHOP', '0007_wishlist_wishlistitem'),
        ('BRYSHOP', '0017_remove_payment_user_card_delete_usercard'),
    ]

    operations = [
    ]
