input {
  file {
    path => "/var/log/django/django_errors.log"
    start_position => "beginning"
    codec => json
    type => "django"
  }
}

filter {
  if [level] == "ERROR" {
    mutate {
      add_tag => ["error_500"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bryshop-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
